package example;

import example.generated.VolanClient;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class JavaConsumerTest {
    @Test
    void ordinaryBuildCompilesJavaAgainstTheGeneratedClient() {
        try (var db = VolanClient.builder().url("jdbc:h2:mem:maven-java;DB_CLOSE_DELAY=-1").build()) {
            db.rawExecute("CREATE TABLE \"User\" (\"id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"name\" VARCHAR NOT NULL)");
            var row = db.getUser().create(data -> data.setName("Maven"));
            assertEquals(row, db.getUser().findFirstOrThrow());
        }
    }
}
