// Generated by Volan from schema.volan. Do not edit: regenerate instead.
package com.example.blog

import io.github.thirtyeighttwentysix.volan.runtime.VolanMappingException
import kotlin.String
import kotlin.jvm.JvmStatic

/**
 * What a person is allowed to do.
 */
public enum class Role(
  /**
   * The value stored in the database, which `@map` can make differ from the name.
   */
  public val databaseValue: String,
) {
  USER("USER"),
  ADMIN("administrator"),
  ;

  public companion object {
    /**
     * Returns the value stored as [value].
     *
     * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanMappingException if the database holds something this enum has no value for.
     */
    @JvmStatic
    public fun fromDatabaseValue(`value`: String): Role = when (value) {
      "USER" -> USER
      "administrator" -> ADMIN
      else -> throw VolanMappingException("""`Role` has no value stored as `$value`. The database holds a value this schema does not know about.""")
    }
  }
}
