// Generated by Volan from schema.volan. Do not edit: regenerate instead.
package com.example.blog

import io.github.thirtyeighttwentysix.volan.runtime.ColumnMetadata
import io.github.thirtyeighttwentysix.volan.runtime.CreateSpec
import io.github.thirtyeighttwentysix.volan.runtime.DeleteSpec
import io.github.thirtyeighttwentysix.volan.runtime.FilterScope
import io.github.thirtyeighttwentysix.volan.runtime.IncludeScope
import io.github.thirtyeighttwentysix.volan.runtime.OrderField
import io.github.thirtyeighttwentysix.volan.runtime.OrderScope
import io.github.thirtyeighttwentysix.volan.runtime.OrderedFilterField
import io.github.thirtyeighttwentysix.volan.runtime.QueryExecutor
import io.github.thirtyeighttwentysix.volan.runtime.QueryScope
import io.github.thirtyeighttwentysix.volan.runtime.RelationMetadata
import io.github.thirtyeighttwentysix.volan.runtime.RelationQuantifier
import io.github.thirtyeighttwentysix.volan.runtime.RelationSlot
import io.github.thirtyeighttwentysix.volan.runtime.Row
import io.github.thirtyeighttwentysix.volan.runtime.RowMapper
import io.github.thirtyeighttwentysix.volan.runtime.SelectScope
import io.github.thirtyeighttwentysix.volan.runtime.SelectedFields
import io.github.thirtyeighttwentysix.volan.runtime.TableMetadata
import io.github.thirtyeighttwentysix.volan.runtime.TextFilterField
import io.github.thirtyeighttwentysix.volan.runtime.UpdateSpec
import io.github.thirtyeighttwentysix.volan.runtime.UpsertSpec
import io.github.thirtyeighttwentysix.volan.runtime.VolanNotFoundException
import io.github.thirtyeighttwentysix.volan.runtime.VolanValidationException
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableList
import kotlin.collections.MutableSet
import kotlin.collections.Set
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

/**
 * One row of `Tag`.
 */
public class Tag(
  /**
   * The `id` column.
   */
  public val id: Int,
  /**
   * The `name` column.
   */
  public val name: String,
  private val postsSlot: RelationSlot<List<Post>> = RelationSlot.notLoaded(),
) {
  /**
   * The `Post` rows this row relates to.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanRelationNotLoadedException if the query did not `include` it.
   */
  public val posts: List<Post>
    get() = postsSlot.get("Tag", "posts")

  /**
   * The same rows, or `null` when the query did not load them.
   */
  public val postsIfLoaded: List<Post>?
    get() = postsSlot.orNull()

  /**
   * Whether the query loaded `posts`.
   */
  public val isPostsLoaded: Boolean
    get() = postsSlot.isLoaded

  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (other !is Tag) return false
    return id == other.id &&
        name == other.name
  }

  override fun hashCode(): Int {
    var result = id.hashCode()
    result = 31 * result + name.hashCode()
    return result
  }

  override fun toString(): String = """Tag(id=$id, name=$name)"""

  /**
   * Builds a [Tag] field by field.
   */
  public class Builder {
    private var idValue: Int? = null

    private var nameValue: String? = null

    /**
     * Sets `id`.
     */
    public fun id(`value`: Int): Builder {
      this.idValue = value
      return this
    }

    /**
     * Sets `name`.
     */
    public fun name(`value`: String): Builder {
      this.nameValue = value
      return this
    }

    /**
     * Builds the entity, failing when a required field was never set.
     */
    public fun build(): Tag = Tag(
      id = requireNotNull(idValue) { "Tag.id is required and was not set" },
      name = requireNotNull(nameValue) { "Tag.name is required and was not set" },
    )
  }

  public companion object {
    /**
     * Starts building a [Tag].
     */
    @JvmStatic
    public fun builder(): Builder = Builder()
  }
}

/**
 * Column names and metadata for `Tag`, as constants.
 */
public object TagTable {
  /**
   * What the runtime knows about `Tag`.
   */
  @JvmField
  public val METADATA: TableMetadata = TableMetadata(
        model = "Tag",
        table = "Tag",
        columns = listOf(
        ColumnMetadata(field = "id", column = "id", isNullable = false, isGenerated = true, isUpdatedAt = false),
        ColumnMetadata(field = "name", column = "name", isNullable = false, isGenerated = false, isUpdatedAt = false),
      ),
        primaryKey = listOf("id"),
        relations = listOf(
        RelationMetadata(field = "posts", target = "Post", isList = true, foreignKeyColumns = emptyList(), referencedColumns = emptyList(), joinTable = "_PostTags"),
      ),
      )

  /**
   * The `id` column.
   */
  @JvmField
  public val ID: String = "id"

  /**
   * The `name` column.
   */
  @JvmField
  public val NAME: String = "name"
}

/**
 * Reads one row of `Tag` into a [Tag].
 */
public object TagRowMapper : RowMapper<Tag> {
  override fun map(row: Row): Tag = Tag(
    id = row.getInt("id"),
    name = row.getString("name"),
  )
}

/**
 * The result of a partial `select` on `Tag`.
 *
 * Fields the query did not select refuse to be read, naming the `select` to change, rather than reading as null.
 */
public class TagProjection(
  private val selected: SelectedFields,
  private val idValue: Int? = null,
  private val nameValue: String? = null,
) {
  /**
   * The `id` column.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanFieldNotSelectedException if the query did not select it.
   */
  public val id: Int
    get() = selected.require<Int>("Tag", "id", idValue)

  /**
   * Whether the query selected `id`.
   */
  public val isIdSelected: Boolean
    get() = selected.contains("id")

  /**
   * The `name` column.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanFieldNotSelectedException if the query did not select it.
   */
  public val name: String
    get() = selected.require<String>("Tag", "name", nameValue)

  /**
   * Whether the query selected `name`.
   */
  public val isNameSelected: Boolean
    get() = selected.contains("name")
}

/**
 * Reads the columns a `select` asked for into a [TagProjection].
 */
public class TagProjectionMapper(
  private val fields: Set<String>,
) : RowMapper<TagProjection> {
  override fun map(row: Row): TagProjection {
    val selection = SelectedFields.of(fields)
    return TagProjection(
      selected = selection,
      idValue = if (fields.contains("id")) row.getInt("id") else null,
      nameValue = if (fields.contains("name")) row.getString("name") else null,
    )
  }
}

/**
 * Conditions on `Tag`. Conditions written one after another mean `AND`.
 */
public class TagWhere : FilterScope() {
  /**
   * Conditions on `Tag.id`.
   */
  public val id: OrderedFilterField<Int> = orderedField("id")

  /**
   * Conditions on `Tag.name`.
   */
  public val name: TextFilterField = textField("name")

  /**
   * Groups the conditions in [block] with `OR`.
   */
  public fun or(block: TagWhere.() -> Unit) {
    recordAnyOf(TagWhere().apply(block))
  }

  /**
   * Groups the conditions in [block] with `AND`.
   */
  public fun and(block: TagWhere.() -> Unit) {
    recordAllOf(TagWhere().apply(block))
  }

  /**
   * Groups the conditions in [block] with `NOT`.
   */
  public fun not(block: TagWhere.() -> Unit) {
    recordNoneOf(TagWhere().apply(block))
  }

  /**
   * Conditions on the related `Post` rows.
   */
  public fun posts(block: TagPostsFilter.() -> Unit) {
    TagPostsFilter { quantifier, nested -> recordRelated("posts", quantifier, nested) }.apply(block)
  }
}

/**
 * How to sort `Tag`. Terms apply in the order they are written.
 */
public class TagOrderBy : OrderScope() {
  /**
   * Sorts on `Tag.id`.
   */
  public val id: OrderField = orderField("id")

  /**
   * Sorts on `Tag.name`.
   */
  public val name: OrderField = orderField("name")
}

/**
 * Which fields of `Tag` to read. Naming a field selects it.
 */
public class TagSelect : SelectScope() {
  /**
   * Selects `id`.
   */
  public val id: Unit
    get() = markSelected("id")

  /**
   * Selects `name`.
   */
  public val name: Unit
    get() = markSelected("name")
}

/**
 * Which relations of `Tag` to load.
 *
 * Each one costs a single extra statement, whatever the size of the result.
 */
public class TagInclude : IncludeScope() {
  /**
   * Loads the related `Post` rows.
   */
  public fun posts(block: PostQuery.() -> Unit = {}) {
    includeRelation("posts", PostQuery().apply(block).build())
  }
}

/**
 * A read of `Tag`: its filter, ordering, paging, projection and relations.
 */
public class TagQuery : QueryScope("Tag") {
  internal var selectedFields: Set<String>? = null

  /**
   * Applies the `where` block.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    recordFilter(TagWhere().apply(block))
  }

  /**
   * Applies the `orderBy` block.
   */
  public fun orderBy(block: TagOrderBy.() -> Unit) {
    recordOrder(TagOrderBy().apply(block))
  }

  /**
   * Applies the `include` block.
   */
  public fun include(block: TagInclude.() -> Unit) {
    recordIncludes(TagInclude().apply(block))
  }

  /**
   * Reads only the named fields.
   *
   * Use it with the `project…` operations, whose result refuses to hand back a field this block left out.
   */
  public fun select(block: TagSelect.() -> Unit) {
    val fields = TagSelect().apply(block).build()
    selectedFields = fields
    recordSelection(fields.map { requireNotNull(TagTable.METADATA.column(it)).column })
  }

  /**
   * Resumes after the row with this key.
   *
   * Cursor paging stays correct while rows are being inserted, which `skip` cannot promise.
   */
  public fun cursor(id: Int, inclusive: Boolean = false) {
    recordCursor(mapOf("id" to id), inclusive)
  }
}

/**
 * The values to insert as a new `Tag`.
 *
 * A field with a default may be left unset; every other field has to be given a value.
 */
public class TagCreateData {
  private val touched: MutableSet<String> = linkedSetOf()

  /**
   * The value for `Tag.id`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var id: Int? = null
    set(`value`) {
      field = value
      touched.add("id")
    }

  /**
   * The value for `Tag.name`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var name: String? = null
    set(`value`) {
      field = value
      touched.add("name")
    }

  /**
   * The values to write, keyed by column name.
   */
  internal fun toValues(): Map<String, Any?> {
    val values = LinkedHashMap<String, Any?>()
    if (touched.contains("id")) {
      values["id"] = (id ?: throw VolanValidationException("Tag.id cannot be set to null"))
    }
    if (touched.contains("name")) {
      values["name"] = (name ?: throw VolanValidationException("Tag.name cannot be set to null"))
    } else {
      throw VolanValidationException("Tag.name is required and was not set")
    }
    return values
  }
}

/**
 * The values to change on a `Tag`.
 *
 * Only the fields this block mentions are written; everything else is left alone.
 */
public class TagUpdateData {
  private val touched: MutableSet<String> = linkedSetOf()

  /**
   * The value for `Tag.id`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var id: Int? = null
    set(`value`) {
      field = value
      touched.add("id")
    }

  /**
   * The value for `Tag.name`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var name: String? = null
    set(`value`) {
      field = value
      touched.add("name")
    }

  /**
   * The values to write, keyed by column name.
   */
  internal fun toValues(): Map<String, Any?> {
    val values = LinkedHashMap<String, Any?>()
    if (touched.contains("id")) {
      values["id"] = (id ?: throw VolanValidationException("Tag.id cannot be set to null"))
    }
    if (touched.contains("name")) {
      values["name"] = (name ?: throw VolanValidationException("Tag.name cannot be set to null"))
    }
    return values
  }
}

/**
 * Several `Tag` rows to insert in one statement.
 */
public class TagCreateMany {
  internal val rows: MutableList<CreateSpec> = mutableListOf()

  /**
   * Adds one row to insert.
   */
  public fun row(block: TagCreateData.() -> Unit) {
    rows.add(CreateSpec("Tag", TagCreateData().apply(block).toValues()))
  }
}

/**
 * Which `Tag` rows to change, and what to change on them.
 */
public class TagUpdateScope {
  internal val filter: TagWhere = TagWhere()

  internal val payload: TagUpdateData = TagUpdateData()

  /**
   * Which rows to change.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    filter.apply(block)
  }

  /**
   * What to change.
   */
  public fun `data`(block: TagUpdateData.() -> Unit) {
    payload.apply(block)
  }
}

/**
 * Which `Tag` row to look for, what to insert when it is missing, what to change when it is not.
 */
public class TagUpsertScope {
  internal val filter: TagWhere = TagWhere()

  internal val insert: TagCreateData = TagCreateData()

  internal val patch: TagUpdateData = TagUpdateData()

  /**
   * Which row to look for.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    filter.apply(block)
  }

  /**
   * What to insert when there is none.
   */
  public fun create(block: TagCreateData.() -> Unit) {
    insert.apply(block)
  }

  /**
   * What to change when there is one.
   */
  public fun update(block: TagUpdateData.() -> Unit) {
    patch.apply(block)
  }
}

/**
 * Which `Tag` rows to delete.
 */
public class TagDeleteScope {
  internal val filter: TagWhere = TagWhere()

  /**
   * Which rows to delete.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    filter.apply(block)
  }
}

/**
 * Reads and writes `Tag`.
 */
public class TagRepository(
  private val executor: QueryExecutor,
) {
  /**
   * Reads every matching row.
   */
  public fun findMany(block: TagQuery.() -> Unit = {}): List<Tag> = executor.findMany(TagQuery().apply(block).build(), TagRowMapper)

  /**
   * Reads the first matching row, or `null`.
   */
  public fun findFirst(block: TagQuery.() -> Unit = {}): Tag? = executor.findFirst(TagQuery().apply(block).build(), TagRowMapper)

  /**
   * Like [findFirst], but fails instead of returning `null`.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanNotFoundException if nothing matched the query.
   */
  public fun findFirstOrThrow(block: TagQuery.() -> Unit = {}): Tag = findFirst(block) ?: throw VolanNotFoundException("Tag", "no Tag matched the query")

  /**
   * Reads the row a unique key selects, or `null`.
   */
  public fun findUnique(block: TagQuery.() -> Unit = {}): Tag? = executor.findFirst(TagQuery().apply(block).build(), TagRowMapper)

  /**
   * Like [findUnique], but fails instead of returning `null`.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanNotFoundException if nothing matched the unique key.
   */
  public fun findUniqueOrThrow(block: TagQuery.() -> Unit = {}): Tag = findUnique(block) ?: throw VolanNotFoundException("Tag", "no Tag matched the unique key")

  /**
   * Counts the matching rows.
   */
  public fun count(block: TagQuery.() -> Unit = {}): Long = executor.count(TagQuery().apply(block).build())

  /**
   * Whether any row matches.
   */
  public fun exists(block: TagQuery.() -> Unit = {}): Boolean = executor.exists(TagQuery().apply(block).build())

  /**
   * Reads only the selected fields of every matching row.
   *
   * Fields the `select` block leaves out refuse to be read from the result.
   */
  public fun projectMany(block: TagQuery.() -> Unit): List<TagProjection> {
    val query = TagQuery().apply(block)
    return executor.findMany(query.build(), TagProjectionMapper(query.selectedFields ?: ALL_FIELDS))
  }

  /**
   * Reads only the selected fields of the first matching row.
   *
   * Fields the `select` block leaves out refuse to be read from the result.
   */
  public fun projectFirst(block: TagQuery.() -> Unit): TagProjection? {
    val query = TagQuery().apply(block)
    return executor.findFirst(query.build(), TagProjectionMapper(query.selectedFields ?: ALL_FIELDS))
  }

  /**
   * Inserts one row and reads it back.
   */
  public fun create(block: TagCreateData.() -> Unit): Tag = executor.create(CreateSpec("Tag", TagCreateData().apply(block).toValues()), TagRowMapper)

  /**
   * Inserts several rows, returning how many were written.
   */
  public fun createMany(block: TagCreateMany.() -> Unit): Long = executor.createMany(TagCreateMany().apply(block).rows)

  /**
   * Changes the single row the `where` block selects and reads it back.
   */
  public fun update(block: TagUpdateScope.() -> Unit): Tag {
    val scope = TagUpdateScope().apply(block)
    return executor.update(UpdateSpec("Tag", scope.filter.build(), scope.payload.toValues()), TagRowMapper)
  }

  /**
   * Changes every row the `where` block selects, returning how many changed.
   */
  public fun updateMany(block: TagUpdateScope.() -> Unit): Long {
    val scope = TagUpdateScope().apply(block)
    return executor.updateMany(UpdateSpec("Tag", scope.filter.build(), scope.payload.toValues()))
  }

  /**
   * Changes the row the `where` block selects, or inserts one when there is none.
   */
  public fun upsert(block: TagUpsertScope.() -> Unit): Tag {
    val scope = TagUpsertScope().apply(block)
    return executor.upsert(UpsertSpec("Tag", scope.filter.build(), scope.insert.toValues(), scope.patch.toValues()), TagRowMapper)
  }

  /**
   * Deletes the single row the `where` block selects and reads back what was removed.
   */
  public fun delete(block: TagDeleteScope.() -> Unit): Tag {
    val scope = TagDeleteScope().apply(block)
    return executor.delete(DeleteSpec("Tag", scope.filter.build()), TagRowMapper)
  }

  /**
   * Deletes every row the `where` block selects, returning how many were removed.
   */
  public fun deleteMany(block: TagDeleteScope.() -> Unit): Long {
    val scope = TagDeleteScope().apply(block)
    return executor.deleteMany(DeleteSpec("Tag", scope.filter.build()))
  }

  public companion object {
    private val ALL_FIELDS: Set<String> = setOf("id", "name")
  }
}

/**
 * How the related `Post` rows have to match.
 */
public class TagPostsFilter(
  private val sink: (RelationQuantifier, FilterScope) -> Unit,
) {
  /**
   * Matches when at least one related `Post` matches.
   */
  public fun some(block: PostWhere.() -> Unit) {
    sink(RelationQuantifier.SOME, PostWhere().apply(block))
  }

  /**
   * Matches when every related `Post` matches.
   */
  public fun every(block: PostWhere.() -> Unit) {
    sink(RelationQuantifier.EVERY, PostWhere().apply(block))
  }

  /**
   * Matches when no related `Post` matches.
   */
  public fun none(block: PostWhere.() -> Unit) {
    sink(RelationQuantifier.NONE, PostWhere().apply(block))
  }
}
