// Generated by Volan from schema.volan. Do not edit: regenerate instead.
package com.example.blog

import io.github.thirtyeighttwentysix.volan.runtime.AggregateFunction
import io.github.thirtyeighttwentysix.volan.runtime.AggregateScope
import io.github.thirtyeighttwentysix.volan.runtime.AggregateValues
import io.github.thirtyeighttwentysix.volan.runtime.ColumnMetadata
import io.github.thirtyeighttwentysix.volan.runtime.ConnectOrCreateEntry
import io.github.thirtyeighttwentysix.volan.runtime.CreateSpec
import io.github.thirtyeighttwentysix.volan.runtime.DeleteSpec
import io.github.thirtyeighttwentysix.volan.runtime.EntityReader
import io.github.thirtyeighttwentysix.volan.runtime.Filter
import io.github.thirtyeighttwentysix.volan.runtime.FilterScope
import io.github.thirtyeighttwentysix.volan.runtime.GroupScope
import io.github.thirtyeighttwentysix.volan.runtime.HavingScope
import io.github.thirtyeighttwentysix.volan.runtime.IncludeScope
import io.github.thirtyeighttwentysix.volan.runtime.NestedWrite
import io.github.thirtyeighttwentysix.volan.runtime.NestedWrites
import io.github.thirtyeighttwentysix.volan.runtime.OrderField
import io.github.thirtyeighttwentysix.volan.runtime.OrderScope
import io.github.thirtyeighttwentysix.volan.runtime.OrderedFilterField
import io.github.thirtyeighttwentysix.volan.runtime.QueryExecutor
import io.github.thirtyeighttwentysix.volan.runtime.QueryScope
import io.github.thirtyeighttwentysix.volan.runtime.RelationMetadata
import io.github.thirtyeighttwentysix.volan.runtime.RelationQuantifier
import io.github.thirtyeighttwentysix.volan.runtime.RelationSlot
import io.github.thirtyeighttwentysix.volan.runtime.Row
import io.github.thirtyeighttwentysix.volan.runtime.RowMapper
import io.github.thirtyeighttwentysix.volan.runtime.SelectScope
import io.github.thirtyeighttwentysix.volan.runtime.SelectedFields
import io.github.thirtyeighttwentysix.volan.runtime.TableMetadata
import io.github.thirtyeighttwentysix.volan.runtime.TextFilterField
import io.github.thirtyeighttwentysix.volan.runtime.UpdateSpec
import io.github.thirtyeighttwentysix.volan.runtime.UpsertSpec
import io.github.thirtyeighttwentysix.volan.runtime.VolanConfigurationException
import io.github.thirtyeighttwentysix.volan.runtime.VolanNotFoundException
import io.github.thirtyeighttwentysix.volan.runtime.VolanValidationException
import java.math.BigDecimal
import kotlin.Any
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.MutableList
import kotlin.collections.MutableSet
import kotlin.collections.Set
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

/**
 * One row of `Tag`.
 */
public class Tag(
  /**
   * The `id` column.
   */
  public val id: Int,
  /**
   * The `name` column.
   */
  public val name: String,
  private val postsSlot: RelationSlot<List<Post>> = RelationSlot.notLoaded(),
) {
  /**
   * The `Post` rows this row relates to.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanRelationNotLoadedException if the query did not `include` it.
   */
  public val posts: List<Post>
    get() = postsSlot.get("Tag", "posts")

  /**
   * The same rows, or `null` when the query did not load them.
   */
  public val postsIfLoaded: List<Post>?
    get() = postsSlot.orNull()

  /**
   * Whether the query loaded `posts`.
   */
  public val isPostsLoaded: Boolean
    get() = postsSlot.isLoaded

  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (other !is Tag) return false
    return id == other.id &&
        name == other.name
  }

  override fun hashCode(): Int {
    var result = id.hashCode()
    result = 31 * result + name.hashCode()
    return result
  }

  override fun toString(): String = """Tag(id=$id, name=$name)"""

  /**
   * Returns a copy of this row with `relation` loaded to `value`.
   */
  internal fun withRelationValue(relation: String, `value`: Any?): Tag = when (relation) {
    "posts" -> Tag(id, name, postsSlot = RelationSlot.loaded(value as List<Post>))
    else -> this
  }

  /**
   * Builds a [Tag] field by field.
   */
  public class Builder {
    private var idValue: Int? = null

    private var nameValue: String? = null

    /**
     * Sets `id`.
     */
    public fun id(`value`: Int): Builder {
      this.idValue = value
      return this
    }

    /**
     * Sets `name`.
     */
    public fun name(`value`: String): Builder {
      this.nameValue = value
      return this
    }

    /**
     * Builds the entity, failing when a required field was never set.
     */
    public fun build(): Tag = Tag(
      id = requireNotNull(idValue) { "Tag.id is required and was not set" },
      name = requireNotNull(nameValue) { "Tag.name is required and was not set" },
    )
  }

  public companion object {
    /**
     * Starts building a [Tag].
     */
    @JvmStatic
    public fun builder(): Builder = Builder()
  }
}

/**
 * Column names and metadata for `Tag`, as constants.
 */
public object TagTable {
  /**
   * What the runtime knows about `Tag`.
   */
  @JvmField
  public val METADATA: TableMetadata = TableMetadata(
        model = "Tag",
        table = "Tag",
        columns = listOf(
        ColumnMetadata(field = "id", column = "id", isNullable = false, isGenerated = true, isUpdatedAt = false),
        ColumnMetadata(field = "name", column = "name", isNullable = false, isGenerated = false, isUpdatedAt = false),
      ),
        primaryKey = listOf("id"),
        relations = listOf(
        RelationMetadata(field = "posts", target = "Post", isList = true, ownsForeignKey = false, foreignKeyColumns = listOf("id"), referencedColumns = listOf("id"), joinTable = "_PostTags", joinLocalColumns = listOf("B"), joinTargetColumns = listOf("A")),
      ),
      )

  /**
   * Every set of columns that identifies at most one row, most specific first.
   */
  @JvmField
  public val UNIQUE_KEYS: List<List<String>> = listOf(listOf("id"), listOf("name"))

  /**
   * The `id` column.
   */
  @JvmField
  public val ID: String = "id"

  /**
   * The `name` column.
   */
  @JvmField
  public val NAME: String = "name"
}

/**
 * Reads one row of `Tag` into a [Tag], and gives the relation loader the two things it needs: this row's key, and a copy of it with a relation filled in.
 */
public object TagRowMapper : EntityReader<Tag> {
  /**
   * The model these rows belong to.
   */
  override val model: String = "Tag"

  override fun map(row: Row): Tag = Tag(
    id = row.getInt("id"),
    name = row.getString("name"),
  )

  /**
   * Reads the values of `columns` out of `entity`, in order.
   */
  override fun key(entity: Tag, columns: List<String>): List<Any?> = columns.map { column ->
    when (column) {
      "id" -> entity.id
      "name" -> entity.name
      else -> throw VolanConfigurationException("""`Tag` has no column named `$column`, so it cannot be part of a key.""")
    }
  }

  /**
   * Returns a copy of `entity` with `relation` loaded to `value`.
   */
  override fun withRelation(
    entity: Tag,
    relation: String,
    `value`: Any?,
  ): Tag = entity.withRelationValue(relation, value)
}

/**
 * The result of a partial `select` on `Tag`.
 *
 * Fields the query did not select refuse to be read, naming the `select` to change, rather than reading as null.
 */
public class TagProjection(
  private val selected: SelectedFields,
  private val idValue: Int? = null,
  private val nameValue: String? = null,
) {
  /**
   * The `id` column.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanFieldNotSelectedException if the query did not select it.
   */
  public val id: Int
    get() = selected.require<Int>("Tag", "id", idValue)

  /**
   * Whether the query selected `id`.
   */
  public val isIdSelected: Boolean
    get() = selected.contains("id")

  /**
   * The `name` column.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanFieldNotSelectedException if the query did not select it.
   */
  public val name: String
    get() = selected.require<String>("Tag", "name", nameValue)

  /**
   * Whether the query selected `name`.
   */
  public val isNameSelected: Boolean
    get() = selected.contains("name")
}

/**
 * Reads the columns a `select` or a `by` asked for into a [TagProjection].
 */
public class TagProjectionMapper(
  private val selected: SelectedFields,
) : RowMapper<TagProjection> {
  override fun map(row: Row): TagProjection = TagProjection(
    selected = selected,
    idValue = if (selected.contains("id")) row.getInt("id") else null,
    nameValue = if (selected.contains("name")) row.getString("name") else null,
  )
}

/**
 * Conditions on `Tag`. Conditions written one after another mean `AND`.
 */
public class TagWhere : FilterScope() {
  /**
   * Conditions on `Tag.id`.
   */
  public val id: OrderedFilterField<Int> = orderedField("id")

  /**
   * Conditions on `Tag.name`.
   */
  public val name: TextFilterField = textField("name")

  /**
   * Groups the conditions in [block] with `OR`.
   */
  public fun or(block: TagWhere.() -> Unit) {
    recordAnyOf(TagWhere().apply(block))
  }

  /**
   * Groups the conditions in [block] with `AND`.
   */
  public fun and(block: TagWhere.() -> Unit) {
    recordAllOf(TagWhere().apply(block))
  }

  /**
   * Groups the conditions in [block] with `NOT`.
   */
  public fun not(block: TagWhere.() -> Unit) {
    recordNoneOf(TagWhere().apply(block))
  }

  /**
   * Conditions on the related `Post` rows.
   */
  public fun posts(block: TagPostsFilter.() -> Unit) {
    TagPostsFilter { quantifier, nested -> recordRelated("posts", quantifier, nested) }.apply(block)
  }
}

/**
 * How to sort `Tag`. Terms apply in the order they are written.
 */
public class TagOrderBy : OrderScope() {
  /**
   * Sorts on `Tag.id`.
   */
  public val id: OrderField = orderField("id")

  /**
   * Sorts on `Tag.name`.
   */
  public val name: OrderField = orderField("name")
}

/**
 * Which fields of `Tag` to read. Naming a field selects it.
 */
public class TagSelect : SelectScope() {
  /**
   * Selects `id`.
   */
  public val id: Unit
    get() = markSelected("id")

  /**
   * Selects `name`.
   */
  public val name: Unit
    get() = markSelected("name")
}

/**
 * Which relations of `Tag` to load.
 *
 * Each one costs a single extra statement, whatever the size of the result.
 */
public class TagInclude : IncludeScope() {
  /**
   * Loads the related `Post` rows.
   */
  public fun posts(block: PostQuery.() -> Unit = {}) {
    includeRelation("posts", PostQuery().apply(block).build())
  }
}

/**
 * The fields of `Tag`, for the blocks that name some of them.
 */
public class TagFields : SelectScope() {
  /**
   * Names `id`.
   */
  public val id: Unit
    get() = markSelected("id")

  /**
   * Names `name`.
   */
  public val name: Unit
    get() = markSelected("name")
}

/**
 * A read of `Tag`: its filter, ordering, paging, projection and relations.
 */
public class TagQuery : QueryScope("Tag") {
  internal var selectedFields: Set<String>? = null

  /**
   * Applies the `where` block.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    recordFilter(TagWhere().apply(block))
  }

  /**
   * Applies the `orderBy` block.
   */
  public fun orderBy(block: TagOrderBy.() -> Unit) {
    recordOrder(TagOrderBy().apply(block))
  }

  /**
   * Applies the `include` block.
   */
  public fun include(block: TagInclude.() -> Unit) {
    recordIncludes(TagInclude().apply(block))
  }

  /**
   * Reads only the named fields.
   *
   * Use it with the `project…` operations, whose result refuses to hand back a field this block left out.
   */
  public fun select(block: TagSelect.() -> Unit) {
    val fields = TagSelect().apply(block).build()
    selectedFields = fields
    recordSelection(fields.map { requireNotNull(TagTable.METADATA.column(it)).column })
  }

  /**
   * Returns only rows that differ in the named fields.
   *
   * With no fields named, nothing is de-duplicated: the query returns every matching row.
   */
  public fun distinct(block: TagFields.() -> Unit) {
    recordDistinct(TagFields().apply(block).build().map { requireNotNull(TagTable.METADATA.column(it)).column })
  }

  /**
   * Resumes after the row with this key.
   *
   * Cursor paging stays correct while rows are being inserted, which `skip` cannot promise.
   */
  public fun cursor(id: Int, inclusive: Boolean = false) {
    recordCursor(mapOf("id" to id), inclusive)
  }
}

/**
 * The fields of `Tag` that can be totalled or averaged.
 */
public class TagNumericFields : SelectScope() {
  /**
   * Summarises `id`.
   */
  public val id: Unit
    get() = markSelected("id")
}

/**
 * The fields of `Tag` that have a smallest and a largest value.
 */
public class TagOrderedFields : SelectScope() {
  /**
   * Summarises `id`.
   */
  public val id: Unit
    get() = markSelected("id")

  /**
   * Summarises `name`.
   */
  public val name: Unit
    get() = markSelected("name")
}

/**
 * What to work out about `Tag`, and over which rows.
 */
public class TagAggregateScope : AggregateScope("Tag") {
  /**
   * Which rows to summarise.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    recordFilter(TagWhere().apply(block))
  }

  /**
   * Counts the matching rows.
   */
  public fun count() {
    record(AggregateFunction.COUNT, null, "count")
  }

  /**
   * Totals the named fields.
   */
  public fun sum(block: TagNumericFields.() -> Unit) {
    TagNumericFields().apply(block).build().forEach { field ->
      record(AggregateFunction.SUM, requireNotNull(TagTable.METADATA.column(field)).column, "sum_" + field)
    }
  }

  /**
   * Averages the named fields.
   */
  public fun average(block: TagNumericFields.() -> Unit) {
    TagNumericFields().apply(block).build().forEach { field ->
      record(AggregateFunction.AVERAGE, requireNotNull(TagTable.METADATA.column(field)).column, "avg_" + field)
    }
  }

  /**
   * Takes the smallest value of the named fields.
   */
  public fun minimum(block: TagOrderedFields.() -> Unit) {
    TagOrderedFields().apply(block).build().forEach { field ->
      record(AggregateFunction.MINIMUM, requireNotNull(TagTable.METADATA.column(field)).column, "min_" + field)
    }
  }

  /**
   * Takes the largest value of the named fields.
   */
  public fun maximum(block: TagOrderedFields.() -> Unit) {
    TagOrderedFields().apply(block).build().forEach { field ->
      record(AggregateFunction.MAXIMUM, requireNotNull(TagTable.METADATA.column(field)).column, "max_" + field)
    }
  }
}

/**
 * What a query worked out about `Tag`.
 *
 * A summary the query did not ask for refuses to be read, rather than reading as zero — zero being a perfectly good answer to a question that was asked.
 */
public class TagAggregate(
  private val values: Map<String, Any?>,
) {
  /**
   * How many rows there are.
   */
  public val count: Long
    get() = AggregateValues.count(values, "count", "how many `Tag` rows there are")

  /**
   * The total of `Tag.id`.
   */
  public val sumOfId: BigDecimal?
    get() = AggregateValues.decimal(values, "sum_id", "the total of `Tag.id`")

  /**
   * The mean of `Tag.id`.
   */
  public val averageOfId: Double?
    get() = AggregateValues.double(values, "avg_id", "the mean of `Tag.id`")

  /**
   * The smallest value of `Tag.id`.
   */
  public val minimumOfId: Int?
    get() = AggregateValues.int(values, "min_id", "the smallest value of `Tag.id`")

  /**
   * The largest value of `Tag.id`.
   */
  public val maximumOfId: Int?
    get() = AggregateValues.int(values, "max_id", "the largest value of `Tag.id`")

  /**
   * The smallest value of `Tag.name`.
   */
  public val minimumOfName: String?
    get() = AggregateValues.string(values, "min_name", "the smallest value of `Tag.name`")

  /**
   * The largest value of `Tag.name`.
   */
  public val maximumOfName: String?
    get() = AggregateValues.string(values, "max_name", "the largest value of `Tag.name`")
}

/**
 * Which groups of `Tag` survive, written over what was worked out about them.
 *
 * Only summaries are on offer here. A condition on a grouped field is the same condition on the rows that went into the group, which is what `where` is for — and `where` narrows before the grouping work is done rather than after it.
 */
public class TagHaving : HavingScope() {
  /**
   * How many rows are in the group.
   */
  public val count: OrderedFilterField<Long> =
      aggregateField(AggregateFunction.COUNT, null, "count")

  /**
   * The total of `id` across the group.
   */
  public val sumOfId: OrderedFilterField<BigDecimal> =
      aggregateField(AggregateFunction.SUM, "id", "sum_id")

  /**
   * The mean of `id` across the group.
   */
  public val averageOfId: OrderedFilterField<Double> =
      aggregateField(AggregateFunction.AVERAGE, "id", "avg_id")

  /**
   * The smallest value of `id` across the group.
   */
  public val minimumOfId: OrderedFilterField<Int> =
      aggregateField(AggregateFunction.MINIMUM, "id", "min_id")

  /**
   * The largest value of `id` across the group.
   */
  public val maximumOfId: OrderedFilterField<Int> =
      aggregateField(AggregateFunction.MAXIMUM, "id", "max_id")

  /**
   * The smallest value of `name` across the group.
   */
  public val minimumOfName: OrderedFilterField<String> =
      aggregateField(AggregateFunction.MINIMUM, "name", "min_name")

  /**
   * The largest value of `name` across the group.
   */
  public val maximumOfName: OrderedFilterField<String> =
      aggregateField(AggregateFunction.MAXIMUM, "name", "max_name")
}

/**
 * How to fold `Tag` into groups, and what to work out about each one.
 */
public class TagGroupScope : GroupScope("Tag") {
  /**
   * The fields whose values define a group.
   */
  public fun `by`(block: TagFields.() -> Unit) {
    recordGrouping(TagFields().apply(block).build())
  }

  /**
   * Which rows go into the groups at all.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    recordFilter(TagWhere().apply(block))
  }

  /**
   * Which groups survive, judged on what was worked out about them.
   */
  public fun having(block: TagHaving.() -> Unit) {
    recordHaving(TagHaving().apply(block))
  }

  /**
   * How to sort the groups, by the fields they are grouped on.
   */
  public fun orderBy(block: TagOrderBy.() -> Unit) {
    recordOrder(TagOrderBy().apply(block))
  }

  /**
   * Counts the matching rows.
   */
  public fun count() {
    record(AggregateFunction.COUNT, null, "count")
  }

  /**
   * Totals the named fields.
   */
  public fun sum(block: TagNumericFields.() -> Unit) {
    TagNumericFields().apply(block).build().forEach { field ->
      record(AggregateFunction.SUM, requireNotNull(TagTable.METADATA.column(field)).column, "sum_" + field)
    }
  }

  /**
   * Averages the named fields.
   */
  public fun average(block: TagNumericFields.() -> Unit) {
    TagNumericFields().apply(block).build().forEach { field ->
      record(AggregateFunction.AVERAGE, requireNotNull(TagTable.METADATA.column(field)).column, "avg_" + field)
    }
  }

  /**
   * Takes the smallest value of the named fields.
   */
  public fun minimum(block: TagOrderedFields.() -> Unit) {
    TagOrderedFields().apply(block).build().forEach { field ->
      record(AggregateFunction.MINIMUM, requireNotNull(TagTable.METADATA.column(field)).column, "min_" + field)
    }
  }

  /**
   * Takes the largest value of the named fields.
   */
  public fun maximum(block: TagOrderedFields.() -> Unit) {
    TagOrderedFields().apply(block).build().forEach { field ->
      record(AggregateFunction.MAXIMUM, requireNotNull(TagTable.METADATA.column(field)).column, "max_" + field)
    }
  }
}

/**
 * One group of `Tag`: the values that define it, and what was worked out about it.
 *
 * A field the `by` block left out refuses to be read, because the group has no single value for it.
 */
public class TagGroup(
  private val key: TagProjection,
  private val values: Map<String, Any?>,
) {
  /**
   * The value of `id` this group is for.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanFieldNotSelectedException if the query did not group by it.
   */
  public val id: Int
    get() = key.id

  /**
   * Whether the query grouped by `id`.
   */
  public val isIdGrouped: Boolean
    get() = key.isIdSelected

  /**
   * The value of `name` this group is for.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanFieldNotSelectedException if the query did not group by it.
   */
  public val name: String
    get() = key.name

  /**
   * Whether the query grouped by `name`.
   */
  public val isNameGrouped: Boolean
    get() = key.isNameSelected

  /**
   * How many rows are in this group.
   */
  public val count: Long
    get() = AggregateValues.count(values, "count", "how many `Tag` rows are in this group")

  /**
   * The total of `Tag.id`.
   */
  public val sumOfId: BigDecimal?
    get() = AggregateValues.decimal(values, "sum_id", "the total of `Tag.id`")

  /**
   * The mean of `Tag.id`.
   */
  public val averageOfId: Double?
    get() = AggregateValues.double(values, "avg_id", "the mean of `Tag.id`")

  /**
   * The smallest value of `Tag.id`.
   */
  public val minimumOfId: Int?
    get() = AggregateValues.int(values, "min_id", "the smallest value of `Tag.id`")

  /**
   * The largest value of `Tag.id`.
   */
  public val maximumOfId: Int?
    get() = AggregateValues.int(values, "max_id", "the largest value of `Tag.id`")

  /**
   * The smallest value of `Tag.name`.
   */
  public val minimumOfName: String?
    get() = AggregateValues.string(values, "min_name", "the smallest value of `Tag.name`")

  /**
   * The largest value of `Tag.name`.
   */
  public val maximumOfName: String?
    get() = AggregateValues.string(values, "max_name", "the largest value of `Tag.name`")
}

/**
 * The values to insert as a new `Tag`.
 *
 * A field with a default may be left unset; every other field has to be given a value.
 */
public class TagCreateData {
  private val touched: MutableSet<String> = linkedSetOf()

  /**
   * The value for `Tag.id`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var id: Int? = null
    set(`value`) {
      field = value
      touched.add("id")
    }

  /**
   * The value for `Tag.name`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var name: String? = null
    set(`value`) {
      field = value
      touched.add("name")
    }

  private val writes: MutableList<NestedWrite> = mutableListOf()

  /**
   * The `Post` rows on the other side of `posts`.
   */
  public val posts: TagPostsWrite = TagPostsWrite(writes)

  /**
   * The writes to make on the far side of this row's relations, in the order they were asked for.
   */
  internal fun toNested(): List<NestedWrite> = writes.toList()

  /**
   * The values to write, keyed by column name.
   */
  internal fun toValues(): Map<String, Any?> {
    val values = LinkedHashMap<String, Any?>()
    if (touched.contains("id")) {
      values["id"] = (id ?: throw VolanValidationException("Tag.id cannot be set to null"))
    }
    if (touched.contains("name")) {
      values["name"] = (name ?: throw VolanValidationException("Tag.name cannot be set to null"))
    }
    return values
  }
}

/**
 * The values to change on a `Tag`.
 *
 * Only the fields this block mentions are written; everything else is left alone.
 */
public class TagUpdateData {
  private val touched: MutableSet<String> = linkedSetOf()

  /**
   * The value for `Tag.id`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var id: Int? = null
    set(`value`) {
      field = value
      touched.add("id")
    }

  /**
   * The value for `Tag.name`.
   *
   * It is nullable here because it starts out unset; leaving it unset is what null means.
   */
  public var name: String? = null
    set(`value`) {
      field = value
      touched.add("name")
    }

  private val writes: MutableList<NestedWrite> = mutableListOf()

  /**
   * The `Post` rows on the other side of `posts`.
   */
  public val posts: TagPostsChange = TagPostsChange(writes)

  /**
   * The writes to make on the far side of this row's relations, in the order they were asked for.
   */
  internal fun toNested(): List<NestedWrite> = writes.toList()

  /**
   * The values to write, keyed by column name.
   */
  internal fun toValues(): Map<String, Any?> {
    val values = LinkedHashMap<String, Any?>()
    if (touched.contains("id")) {
      values["id"] = (id ?: throw VolanValidationException("Tag.id cannot be set to null"))
    }
    if (touched.contains("name")) {
      values["name"] = (name ?: throw VolanValidationException("Tag.name cannot be set to null"))
    }
    return values
  }
}

/**
 * Several `Tag` rows to insert in one statement.
 */
public class TagCreateMany {
  internal val rows: MutableList<CreateSpec> = mutableListOf()

  /**
   * Adds one row to insert.
   */
  public fun row(block: TagCreateData.() -> Unit) {
    val data = TagCreateData().apply(block)
    NestedWrites.requireFlat("createMany", data.toNested(), "writes its rows in one statement", "Use `create` once per row when the rows bring relations with them.")
    rows.add(CreateSpec("Tag", data.toValues()))
  }
}

/**
 * Which `Tag` rows to change, and what to change on them.
 */
public class TagUpdateScope {
  internal val filter: TagWhere = TagWhere()

  internal val payload: TagUpdateData = TagUpdateData()

  /**
   * Which rows to change.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    filter.apply(block)
  }

  /**
   * What to change.
   */
  public fun `data`(block: TagUpdateData.() -> Unit) {
    payload.apply(block)
  }
}

/**
 * Which `Tag` row to look for, what to insert when it is missing, what to change when it is not.
 */
public class TagUpsertScope {
  internal val filter: TagWhere = TagWhere()

  internal val insert: TagCreateData = TagCreateData()

  internal val patch: TagUpdateData = TagUpdateData()

  /**
   * Which row to look for.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    filter.apply(block)
  }

  /**
   * What to insert when there is none.
   */
  public fun create(block: TagCreateData.() -> Unit) {
    insert.apply(block)
  }

  /**
   * What to change when there is one.
   */
  public fun update(block: TagUpdateData.() -> Unit) {
    patch.apply(block)
  }
}

/**
 * Which `Tag` rows to delete.
 */
public class TagDeleteScope {
  internal val filter: TagWhere = TagWhere()

  /**
   * Which rows to delete.
   */
  public fun `where`(block: TagWhere.() -> Unit) {
    filter.apply(block)
  }
}

/**
 * Reads and writes `Tag`.
 */
public class TagRepository(
  private val executor: QueryExecutor,
) {
  /**
   * Reads every matching row.
   */
  public fun findMany(block: TagQuery.() -> Unit = {}): List<Tag> = executor.findMany(TagQuery().apply(block).build(), TagRowMapper)

  /**
   * Reads the first matching row, or `null`.
   */
  public fun findFirst(block: TagQuery.() -> Unit = {}): Tag? = executor.findFirst(TagQuery().apply(block).build(), TagRowMapper)

  /**
   * Like [findFirst], but fails instead of returning `null`.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanNotFoundException if nothing matched the query.
   */
  public fun findFirstOrThrow(block: TagQuery.() -> Unit = {}): Tag = findFirst(block) ?: throw VolanNotFoundException("Tag", "no Tag matched the query")

  /**
   * Reads the row a unique key selects, or `null`.
   */
  public fun findUnique(block: TagQuery.() -> Unit = {}): Tag? = executor.findFirst(TagQuery().apply(block).build(), TagRowMapper)

  /**
   * Like [findUnique], but fails instead of returning `null`.
   *
   * @throws io.github.thirtyeighttwentysix.volan.runtime.VolanNotFoundException if nothing matched the unique key.
   */
  public fun findUniqueOrThrow(block: TagQuery.() -> Unit = {}): Tag = findUnique(block) ?: throw VolanNotFoundException("Tag", "no Tag matched the unique key")

  /**
   * Counts the matching rows.
   */
  public fun count(block: TagQuery.() -> Unit = {}): Long = executor.count(TagQuery().apply(block).build())

  /**
   * Whether any row matches.
   */
  public fun exists(block: TagQuery.() -> Unit = {}): Boolean = executor.exists(TagQuery().apply(block).build())

  /**
   * Reads only the selected fields of every matching row.
   *
   * Fields the `select` block leaves out refuse to be read from the result.
   */
  public fun projectMany(block: TagQuery.() -> Unit): List<TagProjection> {
    val query = TagQuery().apply(block)
    return executor.findMany(query.build(), TagProjectionMapper(SelectedFields.of(query.selectedFields ?: ALL_FIELDS)))
  }

  /**
   * Reads only the selected fields of the first matching row.
   *
   * Fields the `select` block leaves out refuse to be read from the result.
   */
  public fun projectFirst(block: TagQuery.() -> Unit): TagProjection? {
    val query = TagQuery().apply(block)
    return executor.findFirst(query.build(), TagProjectionMapper(SelectedFields.of(query.selectedFields ?: ALL_FIELDS)))
  }

  /**
   * Works out summaries over the matching rows, in one statement.
   *
   * Only what the block asks for comes back; reading anything else from the result says so.
   */
  public fun aggregate(block: TagAggregateScope.() -> Unit): TagAggregate = TagAggregate(executor.aggregate(TagAggregateScope().apply(block).build()))

  /**
   * Folds the matching rows into groups and summarises each one, in one statement.
   *
   * A group carries values only for the fields the `by` block named; reading any other field of it says so.
   */
  public fun groupBy(block: TagGroupScope.() -> Unit): List<TagGroup> {
    val scope = TagGroupScope().apply(block)
    val mapper = TagProjectionMapper(SelectedFields.groupedBy(scope.groupedFields()))
    return executor.groupBy(scope.build(), mapper).map { TagGroup(it.key, it.values) }
  }

  /**
   * Inserts one row and reads it back.
   *
   * Anything the block asks to write on the far side of a relation is written in the same transaction, so either the whole shape lands or none of it does.
   */
  public fun create(block: TagCreateData.() -> Unit): Tag {
    val data = TagCreateData().apply(block)
    return executor.create(CreateSpec("Tag", data.toValues(), data.toNested()), TagRowMapper)
  }

  /**
   * Inserts several rows, returning how many were written.
   */
  public fun createMany(block: TagCreateMany.() -> Unit): Long = executor.createMany(TagCreateMany().apply(block).rows)

  /**
   * Changes the single row the `where` block selects and reads it back.
   *
   * Anything the block asks of the rows on the far side of a relation happens in the same transaction, so either the whole shape moves or none of it does.
   */
  public fun update(block: TagUpdateScope.() -> Unit): Tag {
    val scope = TagUpdateScope().apply(block)
    return executor.update(UpdateSpec("Tag", scope.filter.build(), scope.payload.toValues(), scope.payload.toNested()), TagRowMapper)
  }

  /**
   * Changes every row the `where` block selects, returning how many changed.
   */
  public fun updateMany(block: TagUpdateScope.() -> Unit): Long {
    val scope = TagUpdateScope().apply(block)
    NestedWrites.requireFlat("updateMany", scope.payload.toNested(), "changes every matching row, so it has no single row to reach out from", "Use `update` on the row itself when it reaches into its relations.")
    return executor.updateMany(UpdateSpec("Tag", scope.filter.build(), scope.payload.toValues()))
  }

  /**
   * Changes the row the `where` block selects, or inserts one when there is none.
   */
  public fun upsert(block: TagUpsertScope.() -> Unit): Tag {
    val scope = TagUpsertScope().apply(block)
    NestedWrites.requireFlat("upsert", scope.insert.toNested(), "decides between two payloads before it writes anything", "Use `update` on the row itself when it reaches into its relations.")
    NestedWrites.requireFlat("upsert", scope.patch.toNested(), "decides between two payloads before it writes anything", "Use `update` on the row itself when it reaches into its relations.")
    return executor.upsert(UpsertSpec("Tag", scope.filter.build(), scope.insert.toValues(), scope.patch.toValues()), TagRowMapper)
  }

  /**
   * Deletes the single row the `where` block selects and reads back what was removed.
   */
  public fun delete(block: TagDeleteScope.() -> Unit): Tag {
    val scope = TagDeleteScope().apply(block)
    return executor.delete(DeleteSpec("Tag", scope.filter.build()), TagRowMapper)
  }

  /**
   * Deletes every row the `where` block selects, returning how many were removed.
   */
  public fun deleteMany(block: TagDeleteScope.() -> Unit): Long {
    val scope = TagDeleteScope().apply(block)
    return executor.deleteMany(DeleteSpec("Tag", scope.filter.build()))
  }

  public companion object {
    private val ALL_FIELDS: Set<String> = setOf("id", "name")
  }
}

/**
 * How the related `Post` rows have to match.
 */
public class TagPostsFilter(
  private val sink: (RelationQuantifier, FilterScope) -> Unit,
) {
  /**
   * Matches when at least one related `Post` matches.
   */
  public fun some(block: PostWhere.() -> Unit) {
    sink(RelationQuantifier.SOME, PostWhere().apply(block))
  }

  /**
   * Matches when every related `Post` matches.
   */
  public fun every(block: PostWhere.() -> Unit) {
    sink(RelationQuantifier.EVERY, PostWhere().apply(block))
  }

  /**
   * Matches when no related `Post` matches.
   */
  public fun none(block: PostWhere.() -> Unit) {
    sink(RelationQuantifier.NONE, PostWhere().apply(block))
  }
}

/**
 * The `Post` rows to write together with a new `Tag`.
 */
public class TagPostsWrite internal constructor(
  internal val writes: MutableList<NestedWrite>,
) {
  /**
   * Writes a new `Post` and attaches it.
   */
  public fun create(block: PostCreateData.() -> Unit) {
    val data = PostCreateData().apply(block)
    writes.add(NestedWrite.CreateRows("posts", listOf(CreateSpec("Post", data.toValues(), data.toNested()))))
  }

  /**
   * Attaches an existing `Post`, which the condition must select.
   */
  public fun connect(block: PostWhere.() -> Unit) {
    val filter = PostWhere().apply(block).build() ?: throw VolanValidationException("`connect` on `Tag.posts` needs a condition saying which `Post` to attach.")
    writes.add(NestedWrite.ConnectRows("posts", listOf(filter)))
  }

  /**
   * Attaches the `Post` these values identify, writing it first if it is not there.
   */
  public fun connectOrCreate(block: PostCreateData.() -> Unit) {
    val data = PostCreateData().apply(block)
    val values = data.toValues()
    val filter = NestedWrites.uniqueFilter("Post", values, PostTable.UNIQUE_KEYS)
    writes.add(NestedWrite.ConnectOrCreateRows("posts", listOf(ConnectOrCreateEntry(filter, CreateSpec("Post", values, data.toNested())))))
  }
}

/**
 * The `Post` rows on the other side of `Tag.posts`.
 */
public class TagPostsChange internal constructor(
  internal val writes: MutableList<NestedWrite>,
) {
  /**
   * Writes a new `Post` and attaches it.
   */
  public fun create(block: PostCreateData.() -> Unit) {
    val data = PostCreateData().apply(block)
    writes.add(NestedWrite.CreateRows("posts", listOf(CreateSpec("Post", data.toValues(), data.toNested()))))
  }

  /**
   * Attaches an existing `Post`, which the condition must select.
   */
  public fun connect(block: PostWhere.() -> Unit) {
    val filter = PostWhere().apply(block).build() ?: throw VolanValidationException("`connect` on `Tag.posts` needs a condition saying which `Post` to attach.")
    writes.add(NestedWrite.ConnectRows("posts", listOf(filter)))
  }

  /**
   * Attaches the `Post` these values identify, writing it first if it is not there.
   */
  public fun connectOrCreate(block: PostCreateData.() -> Unit) {
    val data = PostCreateData().apply(block)
    val values = data.toValues()
    val filter = NestedWrites.uniqueFilter("Post", values, PostTable.UNIQUE_KEYS)
    writes.add(NestedWrite.ConnectOrCreateRows("posts", listOf(ConnectOrCreateEntry(filter, CreateSpec("Post", values, data.toNested())))))
  }

  /**
   * Lets go of the attached `Post` rows the condition selects, leaving them in the database.
   *
   * An empty block lets go of all of them.
   */
  public fun disconnect(block: PostWhere.() -> Unit = {}) {
    val filter = PostWhere().apply(block).build()
    writes.add(NestedWrite.DisconnectRows("posts", listOfNotNull(filter)))
  }

  /**
   * Makes these the attached `Post` rows, whatever was attached before.
   *
   * Rows that were attached and are not named here are let go of, not deleted.
   */
  public fun `set`(block: TagPostsRows.() -> Unit) {
    val filters = mutableListOf<Filter>()
    TagPostsRows(filters).apply(block)
    writes.add(NestedWrite.SetRows("posts", filters.toList()))
  }

  /**
   * Changes the attached `Post` rows the `where` block selects, or all of them.
   */
  public fun update(block: PostUpdateScope.() -> Unit) {
    val scope = PostUpdateScope().apply(block)
    val data = scope.payload
    NestedWrites.requireFlat("a nested update", data.toNested(), "changes the columns of rows that are already there", "Change them from their own repository when they bring relations with them.")
    writes.add(NestedWrite.UpdateRows("posts", scope.filter.build(), data.toValues()))
  }

  /**
   * Deletes the attached `Post` rows the condition selects.
   *
   * An empty block deletes all of them.
   */
  public fun delete(block: PostWhere.() -> Unit = {}) {
    val filter = PostWhere().apply(block).build()
    writes.add(NestedWrite.DeleteRows("posts", filter))
  }
}

/**
 * The `Post` rows that `Tag.posts` should hold.
 */
public class TagPostsRows internal constructor(
  private val filters: MutableList<Filter>,
) {
  /**
   * Names one `Post` the condition must select.
   */
  public fun row(block: PostWhere.() -> Unit) {
    filters.add(PostWhere().apply(block).build() ?: throw VolanValidationException("a row of `Tag.posts` needs a condition saying which `Post` it is."))
  }
}
