package io.github.thirtyeighttwentysix.volan.dialect.h2

import io.github.thirtyeighttwentysix.volan.dialect.ColumnDefault
import io.github.thirtyeighttwentysix.volan.dialect.ColumnDefinition
import io.github.thirtyeighttwentysix.volan.dialect.ColumnType
import io.github.thirtyeighttwentysix.volan.dialect.DdlStatement
import io.github.thirtyeighttwentysix.volan.dialect.IndexDefinition
import io.github.thirtyeighttwentysix.volan.dialect.SqlAssignment
import io.github.thirtyeighttwentysix.volan.dialect.SqlComparison
import io.github.thirtyeighttwentysix.volan.dialect.SqlCondition
import io.github.thirtyeighttwentysix.volan.dialect.SqlDelete
import io.github.thirtyeighttwentysix.volan.dialect.SqlExpression
import io.github.thirtyeighttwentysix.volan.dialect.SqlInsert
import io.github.thirtyeighttwentysix.volan.dialect.SqlType
import io.github.thirtyeighttwentysix.volan.dialect.SqlUpdate
import io.github.thirtyeighttwentysix.volan.dialect.VolanDialectException
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows

class H2RenderingTest {
    @Test
    fun `writes return rows through delta tables and keep parameter order`() {
        val condition = SqlCondition.Compare(SqlExpression.Column(null, "id"), SqlComparison.EQUAL, SqlExpression.Parameter(4))
        val insert = SqlInsert("order\"table", listOf("name"), listOf(listOf(SqlExpression.Parameter("'unsafe"))), listOf("id", "name"))
        val statement = H2Dialect.render(insert)
        statement.sql shouldBe "SELECT \"id\", \"name\" FROM FINAL TABLE (INSERT INTO \"order\"\"table\" (\"name\") VALUES (?))"
        statement.parameters shouldContainExactly listOf("'unsafe")
        val update = SqlUpdate("t", listOf(SqlAssignment("name", SqlExpression.Parameter("changed"))), condition, listOf("id"))
        H2Dialect.render(update).sql shouldBe "SELECT \"id\" FROM FINAL TABLE (UPDATE \"t\" SET \"name\" = ? WHERE \"id\" = ?)"
        H2Dialect.render(update).parameters shouldContainExactly listOf("changed", 4)
        H2Dialect.render(SqlDelete("t", condition, listOf("id"))).sql shouldBe
            "SELECT \"id\" FROM OLD TABLE (DELETE FROM \"t\" WHERE \"id\" = ?)"
        H2Dialect.render(SqlDelete("t", condition)).sql shouldBe "DELETE FROM \"t\" WHERE \"id\" = ?"
    }

    @Test
    fun `default only inserts remain valid with and without returned rows`() {
        val insert = SqlInsert("t", emptyList(), listOf(emptyList()))
        H2Dialect.render(insert).sql shouldBe "INSERT INTO \"t\" DEFAULT VALUES"
        H2Dialect.render(insert.copy(returning = listOf("id"))).sql shouldBe
            "SELECT \"id\" FROM FINAL TABLE (INSERT INTO \"t\" DEFAULT VALUES)"
    }

    @Test
    fun `DDL declares identity precision and arrays without compatibility mode`() {
        val table = DdlStatement.CreateTable(
            "t",
            listOf(ColumnDefinition("id", ColumnType.Scalar(SqlType.BIGINT), false, autoIncrement = true)),
            null,
        )
        H2Dialect.render(table).single().sql shouldContain "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
        declared(ColumnType.Array(ColumnType.Scalar(SqlType.TIMESTAMP))) shouldContain "TIMESTAMP(9) WITH TIME ZONE ARRAY"
        declared(ColumnType.Array(ColumnType.Scalar(SqlType.TEXT)), ColumnDefault.EmptyArray) shouldContain "DEFAULT ARRAY[]"
        declared(ColumnType.Scalar(SqlType.UUID), ColumnDefault.GeneratedUuid) shouldContain "DEFAULT RANDOM_UUID()"
        declared(ColumnType.Scalar(SqlType.TIMESTAMP), ColumnDefault.CurrentTimestamp) shouldContain "DEFAULT CURRENT_TIMESTAMP(9)"
    }

    @Test
    fun `unsupported DDL fails explicitly`() {
        assertThrows<VolanDialectException> { declared(ColumnType.Native("VarChar", listOf("10"))) }
        assertThrows<VolanDialectException> {
            H2Dialect.render(DdlStatement.CreateIndex("t", IndexDefinition("fts", listOf("text"), fullText = true)))
        }
        assertThrows<VolanDialectException> {
            H2Dialect.render(
                DdlStatement.CreateTable(
                    "t",
                    listOf(ColumnDefinition("id", ColumnType.Scalar(SqlType.UUID), false, autoIncrement = true)),
                    null,
                ),
            )
        }
    }

    @Test
    fun `only private memory pools are restricted and memory connections are not retired`() {
        H2Dialect.poolSize("jdbc:h2:mem:", 8) shouldBe 1
        H2Dialect.poolSize("jdbc:h2:mem:;DB_CLOSE_DELAY=0", 8) shouldBe 1
        H2Dialect.poolSize("jdbc:h2:mem:named", 8) shouldBe 8
        H2Dialect.poolSize("jdbc:h2:file:./data", 8) shouldBe 8
        H2Dialect.connectionMaxLifetime("jdbc:h2:mem:named") shouldBe 0L
        H2Dialect.connectionMaxLifetime("jdbc:h2:file:./data") shouldBe null
        assertThrows<IllegalArgumentException> { H2Dialect.poolSize("jdbc:h2:mem:", 0) }
    }

    private fun declared(type: ColumnType, default: ColumnDefault? = null): String = H2Dialect.render(
        DdlStatement.CreateTable("t", listOf(ColumnDefinition("v", type, false, default)), null),
    ).single().sql
}
