package io.github.thirtyeighttwentysix.volan.codegen

import io.github.thirtyeighttwentysix.volan.ir.Schema
import io.github.thirtyeighttwentysix.volan.ir.SchemaLoader
import io.github.thirtyeighttwentysix.volan.schema.SourceFile
import io.kotest.assertions.withClue
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.junit.jupiter.api.Test

class VolanGeneratorTest {
    private val schema: Schema = load("blog.volan")
    private val files = VolanGenerator.generate(schema).associateBy { it.relativePath.substringAfterLast('/') }

    @Test
    fun `one file per enum and model, plus the client`() {
        files.keys.toList() shouldContainExactly
            listOf("Role.kt", "User.kt", "Profile.kt", "Post.kt", "Tag.kt", "Comment.kt", "VolanClient.kt")
    }

    @Test
    fun `files land in the package the generator block asked for`() {
        VolanGenerator.generate(schema).forEach { it.relativePath shouldContain "com/example/blog/" }
    }

    @Test
    fun `the generated enum matches its golden file`() {
        contents("Role.kt") shouldBe golden("Role.kt")
    }

    @Test
    fun `the generated model matches its golden file`() {
        contents("Tag.kt") shouldBe golden("Tag.kt")
    }

    @Test
    fun `every generated file says it is generated`() {
        files.values.forEach { it.contents shouldContain "Generated by Volan" }
    }

    @Test
    fun `the client exposes one repository per model`() {
        val client = contents("VolanClient.kt")
        listOf("user", "profile", "post", "tag", "comment").forEach {
            withClue(it) { client shouldContain "public val $it:" }
        }
    }

    @Test
    fun `mapped names reach the generated code, and schema names stay in the api`() {
        val user = contents("User.kt")
        user shouldContain "table = \"users\","
        user shouldContain "row.getInt(\"id\")"
        user shouldContain "row.getInstant(\"created_at\")"
        user shouldContain "public val createdAt:"
    }

    @Test
    fun `an updatedAt column is never offered as something to write`() {
        val user = contents("User.kt")
        user shouldContain "public class UserUpdateData"
        user.substringAfter("public class UserUpdateData").substringBefore("public class ") shouldNotContain "updatedAt"
    }

    @Test
    fun `a required field without a default has to be set before a create is sent`() {
        contents("User.kt") shouldContain "User.email is required and was not set"
    }

    @Test
    fun `a field with a default may be left out of a create`() {
        val create = contents("User.kt").substringAfter("public class UserCreateData").substringBefore("public class ")
        create shouldNotContain "User.id is required"
    }

    @Test
    fun `relation filters offer the quantifiers the cardinality allows`() {
        contents("User.kt") shouldContain "public class UserPostsFilter"
        contents("User.kt") shouldContain "RelationQuantifier.SOME"
        contents("User.kt") shouldContain "public class UserProfileFilter"
        contents("User.kt") shouldContain "RelationQuantifier.IS"
    }

    @Test
    fun `a many-to-many relation carries its join table into the metadata`() {
        contents("Tag.kt") shouldContain "joinTable = \"_PostTags\""
    }

    @Test
    fun `a composite key becomes a composite cursor`() {
        val cursor = contents("Comment.kt").substringAfter("public fun cursor(").substringBefore("}")
        cursor shouldContain "postId: Long"
        cursor shouldContain "authorId: Int"
        cursor shouldContain "recordCursor(mapOf(\"postId\" to postId, \"authorId\" to authorId), inclusive)"
    }

    @Test
    fun `models and fields marked ignore are left out entirely`() {
        val edge = VolanGenerator.generate(load("edge.volan"))
        edge.map { it.relativePath.substringAfterLast('/') } shouldContainExactly listOf("Account.kt", "VolanClient.kt")
        edge.single { it.relativePath.endsWith("Account.kt") }.contents shouldNotContain "note"
    }

    @Test
    fun `list columns are read through the array accessor`() {
        val account = VolanGenerator.generate(load("edge.volan")).single { it.relativePath.endsWith("Account.kt") }
        account.contents shouldContain "row.getScalarList(\"labels\").map { it as String }"
        account.contents shouldContain "public val labels: List<String>"
    }

    @Test
    fun `a schema with no kotlin generator cannot be generated from`() {
        val without = load("blog.volan").copy(generators = emptyList())
        val thrown = runCatching { VolanGenerator.generate(without) }.exceptionOrNull()
        (thrown is VolanGenerationException) shouldBe true
        thrown?.message.orEmpty() shouldContain "found 0"
    }

    private fun contents(name: String): String = requireNotNull(files[name]) { "no generated file $name" }.contents

    private fun load(fixture: String): Schema {
        val text = requireNotNull(javaClass.getResourceAsStream("/fixtures/$fixture")) { "missing fixture $fixture" }
            .use { it.readBytes().toString(Charsets.UTF_8) }
            .replace("\r\n", "\n")
        return SchemaLoader.loadOrThrow(SourceFile(fixture, text))
    }

    private fun golden(name: String): String = requireNotNull(javaClass.getResourceAsStream("/golden/$name")) { "missing golden $name" }
        .use { it.readBytes().toString(Charsets.UTF_8) }
        .replace("\r\n", "\n")
}
