package example

import example.generated.VolanClient
import io.github.thirtyeighttwentysix.volan.coroutines.suspendQuery
import io.github.thirtyeighttwentysix.volan.micrometer.MicrometerQueryInterceptor
import io.micrometer.core.instrument.simple.SimpleMeterRegistry
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class CoroutineConsumerTest {
    @Test
    fun `published coroutine and metrics modules work with the automatically generated client`() = runBlocking<Unit> {
        val registry = SimpleMeterRegistry()
        try {
            VolanClient.builder().url("jdbc:h2:mem:gradle-coroutines")
                .interceptor(MicrometerQueryInterceptor(registry)).build().use { db ->
                    db.rawExecute("CREATE TABLE \"User\" (\"id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"name\" VARCHAR NOT NULL)")
                    registry.clear()
                    val created = db.suspendQuery { user.create { name = "Coroutine" } }
                    assertEquals(created, db.suspendQuery { user.findFirstOrThrow() })
                    assertEquals(2L, registry.get("volan.query").tag("outcome", "success").timer().count())
                }
        } finally {
            registry.close()
        }
    }
}
