package example

import example.generated.VolanClient
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class KotlinConsumerTest {
    @Test
    fun `ordinary test builds and uses a generated client`() {
        VolanClient.builder().url("jdbc:h2:mem:gradle-kotlin;DB_CLOSE_DELAY=-1").build().use { db ->
            db.rawExecute("CREATE TABLE \"User\" (\"id\" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"name\" VARCHAR NOT NULL)")
            val created = db.user.create { name = "Kotlin" }
            assertEquals(created, db.user.findFirstOrThrow())
        }
    }
}
