package io.github.thirtyeighttwentysix.volan.migrate

import io.github.thirtyeighttwentysix.volan.dialect.ForeignKeyAction
import io.github.thirtyeighttwentysix.volan.dialect.h2.H2Dialect
import io.github.thirtyeighttwentysix.volan.ir.Provider
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.util.UUID

class H2ReaderTest {
    @Test
    fun `every scalar array default and identity survives introspection and export`() = database { connection ->
        val schema = Fixtures.schema(SCALARS)
        val expected = SchemaMapper.map(schema)
        execute(connection, SchemaDiffer.diff(DatabaseSchema(), expected).render(H2Dialect))
        val sync = DatabaseSync(H2Reader(), H2Dialect)
        H2Reader().read(connection) shouldBe expected
        SchemaMapper.map(Fixtures.schema(sync.pull(connection))) shouldBe expected
        sync.plan(connection, schema).isEmpty shouldBe true
        connection.createStatement().use { it.execute("INSERT INTO \"Value\" DEFAULT VALUES") }
        H2Reader().read(connection) shouldBe expected
    }

    @Test
    fun `composite foreign keys preserve referenced order and actions`() = database { connection ->
        ForeignKeyAction.entries.forEach { action ->
            execute(
                connection,
                listOf(
                    "CREATE TABLE \"Parent\" (a INT NOT NULL, b INT NOT NULL, CONSTRAINT \"Parent_pkey\" PRIMARY KEY(b,a))",
                    "CREATE TABLE \"Child\" (id INT NOT NULL, a INT, b INT, CONSTRAINT \"Child_pkey\" PRIMARY KEY(id), " +
                        "CONSTRAINT \"Child_a_b_fkey\" FOREIGN KEY(a,b) REFERENCES \"Parent\"(a,b) " +
                        "ON DELETE ${action.sql} ON UPDATE ${action.sql})",
                ),
            )
            val database = H2Reader().read(connection)
            val key = database.table("Child")!!.foreignKeys.single()
            key.columns shouldBe listOf("A", "B")
            key.targetColumns shouldBe listOf("A", "B")
            key.onDelete shouldBe if (action == ForeignKeyAction.NO_ACTION) ForeignKeyAction.RESTRICT else action
            key.onUpdate shouldBe key.onDelete
            execute(connection, listOf("DROP TABLE \"Child\"", "DROP TABLE \"Parent\""))
        }
    }

    @Test
    fun `mapped names enums constraints and implicit joins have no schema drift`() = database { connection ->
        val text = requireNotNull(javaClass.getResourceAsStream("/fixtures/blog.volan")).use { it.readBytes().toString(Charsets.UTF_8) }
            .replace("postgresql", "h2").replace(Regex("@db\\.VarChar\\([0-9]+\\)"), "").replace("@@fulltext([title, body])", "")
        val schema = Fixtures.schema(text)
        val expected = SchemaMapper.map(schema)
        execute(connection, SchemaDiffer.diff(DatabaseSchema(), expected).render(H2Dialect))
        H2Reader().read(connection) shouldBe expected
        SchemaMapper.map(Fixtures.schema(DatabaseSync(H2Reader(), H2Dialect).pull(connection))) shouldBe expected
    }

    @Test
    fun `unsupported table column constraint and index semantics are rejected`() {
        val definitions = listOf(
            "CREATE VIEW v AS SELECT 1 AS id",
            "CREATE TEMPORARY TABLE t(id INT)",
            "CREATE TABLE t()",
            "CREATE TABLE t(id SMALLINT)",
            "CREATE TABLE t(id VARCHAR(10))",
            "CREATE TABLE t(id NUMERIC(10,2))",
            "CREATE TABLE t(id TIME(3))",
            "CREATE TABLE t(id TIMESTAMP(9))",
            "CREATE TABLE t(id INT ARRAY[10])",
            "CREATE TABLE t(id INT ARRAY ARRAY)",
            "CREATE TABLE t(id INT GENERATED ALWAYS AS IDENTITY)",
            "CREATE TABLE t(id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 10))",
            "CREATE TABLE t(id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 2))",
            "CREATE TABLE t(id INT GENERATED BY DEFAULT AS IDENTITY(MAXVALUE 100))",
            "CREATE TABLE t(id INT GENERATED BY DEFAULT AS IDENTITY(MINVALUE 0))",
            "CREATE TABLE t(id INT GENERATED BY DEFAULT AS IDENTITY(CYCLE))",
            "CREATE TABLE t(id INT GENERATED BY DEFAULT AS IDENTITY(CACHE 1))",
            "CREATE TABLE t(id INT GENERATED ALWAYS AS (1))",
            "CREATE TABLE t(id INT INVISIBLE)",
            "CREATE TABLE t(id INT DEFAULT 1 DEFAULT ON NULL)",
            "CREATE TABLE t(id INT ON UPDATE 1)",
            "CREATE TABLE t(id INT CHECK(id > 0))",
            "CREATE TABLE t(id INT UNIQUE NULLS NOT DISTINCT)",
            "CREATE DOMAIN custom AS INTEGER; CREATE TABLE t(id custom)",
            "CREATE SEQUENCE manual",
            "CREATE TABLE t(id INT); CREATE SYNONYM alias FOR t",
            "CREATE TABLE t(id INT); CREATE INDEX idx ON t(id DESC)",
            "CREATE TABLE t(id INT); CREATE INDEX idx ON t(id NULLS LAST)",
            "CREATE TABLE t(id INT); CREATE HASH INDEX idx ON t(id)",
            "CREATE TABLE t(id INT); CREATE UNIQUE NULLS NOT DISTINCT INDEX idx ON t(id)",
            "SET MODE PostgreSQL",
            "SET COLLATION ENGLISH",
            "SET DEFAULT_NULL_ORDERING HIGH",
            "SET IGNORECASE TRUE",
        )
        definitions.forEach { sql ->
            database { connection ->
                execute(connection, sql.split(';'))
                shouldThrow<VolanMigrationException> { H2Reader().read(connection) }
            }
        }
    }

    @Test
    fun `unique indexes retain their identity and export refuses constraint substitution`() = database { connection ->
        execute(connection, listOf("CREATE TABLE t(id INT)", "CREATE UNIQUE INDEX idx ON t(id)"))
        val database = H2Reader().read(connection)
        database.tables.single().indexes.single().unique shouldBe true
        shouldThrow<VolanMigrationException> { SchemaWriter.write(database, Provider.H2) }
    }

    @Test
    fun `current schema is isolated and cross schema references are refused`() = database { connection ->
        execute(connection, listOf("CREATE SCHEMA other", "CREATE TABLE other.t(id INT PRIMARY KEY)", "SET SCHEMA other"))
        H2Reader().read(connection).tables.map { it.name } shouldBe listOf("T")
        execute(connection, listOf("SET SCHEMA PUBLIC", "CREATE TABLE t(id INT REFERENCES other.t(id))"))
        shouldThrow<VolanMigrationException> { H2Reader().read(connection) }
    }

    @Test
    fun `journal exclusion is configurable and non H2 connections are rejected`() = database { connection ->
        execute(connection, listOf("CREATE TABLE \"${MigrationJournal.DEFAULT_TABLE}\"(id INT)", "CREATE TABLE custom(id INT)"))
        H2Reader().read(connection).tables.map { it.name } shouldBe listOf("CUSTOM")
        H2Reader("CUSTOM").read(connection).tables.map { it.name } shouldBe listOf(MigrationJournal.DEFAULT_TABLE)
        DriverManager.getConnection("jdbc:sqlite::memory:").use { sqlite ->
            shouldThrow<VolanMigrationException> { H2Reader().read(sqlite) }
        }
    }

    private fun database(block: (Connection) -> Unit) = DriverManager.getConnection("jdbc:h2:mem:${UUID.randomUUID()}").use(block)

    private fun execute(connection: Connection, sql: List<String>) = connection.createStatement().use { statement ->
        sql.forEach { statement.execute(it) }
    }

    private companion object {
        private val SCALARS = """
            datasource db {
              provider = "h2"
              url = env("DATABASE_URL")
            }
            model Value {
              id Long @id @default(autoincrement())
              text String @default("quote'\\x")
              integer Int @default(3)
              big Long @default(4)
              real Float @default(1.25)
              double Double @default(2.5)
              number Decimal @default(1.2)
              flag Boolean @default(true)
              moment DateTime @default(now())
              date Date @default(dbgenerated("DATE '2026-10-01'"))
              time Time @default(dbgenerated("TIME '12:34:56.123456789'"))
              token Uuid @default(uuid())
              document Json @default("{}")
              bytes Bytes?
              strings String[] @default([])
              integers Int[] @default([])
              longs Long[] @default([])
              floats Float[] @default([])
              doubles Double[] @default([])
              decimals Decimal[] @default([])
              flags Boolean[] @default([])
              moments DateTime[] @default([])
              dates Date[] @default([])
              times Time[] @default([])
              tokens Uuid[] @default([])
              jsons Json[] @default([])
              blobs Bytes[] @default([])
              @@index([text, integer])
              @@unique([big, integer])
            }
        """.trimIndent()
    }
}
