package io.github.thirtyeighttwentysix.volan.dialect.h2

import io.github.thirtyeighttwentysix.volan.Json
import io.github.thirtyeighttwentysix.volan.dialect.ColumnChange
import io.github.thirtyeighttwentysix.volan.dialect.ColumnDefault
import io.github.thirtyeighttwentysix.volan.dialect.ColumnType
import io.github.thirtyeighttwentysix.volan.dialect.DdlRenderer
import io.github.thirtyeighttwentysix.volan.dialect.DdlStatement
import io.github.thirtyeighttwentysix.volan.dialect.DialectCapabilities
import io.github.thirtyeighttwentysix.volan.dialect.IndexDefinition
import io.github.thirtyeighttwentysix.volan.dialect.SqlDelete
import io.github.thirtyeighttwentysix.volan.dialect.SqlInsert
import io.github.thirtyeighttwentysix.volan.dialect.SqlStatement
import io.github.thirtyeighttwentysix.volan.dialect.SqlType
import io.github.thirtyeighttwentysix.volan.dialect.SqlUpdate
import io.github.thirtyeighttwentysix.volan.dialect.VolanDialectException
import org.h2.api.ErrorCode
import java.sql.SQLException
import java.time.Instant
import java.time.ZoneOffset

/** H2 2.x in regular mode; data change delta tables return written rows, including database defaults. */
public object H2Dialect : DdlRenderer(
    DialectCapabilities(
        returningClause = true,
        insertOnConflict = false,
        caseInsensitiveLike = false,
        distinctOn = true,
        nullsOrdering = true,
        tupleComparison = true,
        arrayColumns = true,
        maximumParameters = 32_767,
    ),
) {
    override val id: String get() = "h2"

    override val currentTimestamp: String get() = "CURRENT_TIMESTAMP(9)"

    override val generatedUuid: String get() = "RANDOM_UUID()"

    override fun render(insert: SqlInsert): SqlStatement =
        returned(super.render(insert.copy(returning = emptyList())), insert.returning, "FINAL")

    override fun render(update: SqlUpdate): SqlStatement =
        returned(super.render(update.copy(returning = emptyList())), update.returning, "FINAL")

    override fun render(delete: SqlDelete): SqlStatement =
        returned(super.render(delete.copy(returning = emptyList())), delete.returning, "OLD")

    private fun returned(statement: SqlStatement, columns: List<String>, version: String): SqlStatement = if (columns.isEmpty()) {
        statement
    } else {
        statement.copy(
            sql = "SELECT ${columns.joinToString(", ") { quote(it) }} FROM $version TABLE (${statement.sql})",
        )
    }

    override fun typeName(type: SqlType): String = when (type) {
        SqlType.TEXT -> "CHARACTER VARYING"
        SqlType.INTEGER -> "INTEGER"
        SqlType.BIGINT -> "BIGINT"
        SqlType.REAL -> "REAL"
        SqlType.DOUBLE -> "DOUBLE PRECISION"
        SqlType.NUMERIC -> "NUMERIC(65, 30)"
        SqlType.BOOLEAN -> "BOOLEAN"
        SqlType.TIMESTAMP -> "TIMESTAMP(9) WITH TIME ZONE"
        SqlType.DATE -> "DATE"
        SqlType.TIME -> "TIME(9)"
        SqlType.JSON -> "JSON"
        SqlType.UUID -> "UUID"
        SqlType.BLOB -> "BINARY VARYING"
    }

    override fun render(type: ColumnType): String = when (type) {
        is ColumnType.Array -> "${render(type.element)} ARRAY"
        is ColumnType.Native -> throw VolanDialectException("H2 @db type overrides are not supported yet.")
        else -> super.render(type)
    }

    override fun render(default: ColumnDefault): String = if (default == ColumnDefault.EmptyArray) "ARRAY[]" else super.render(default)

    override fun autoIncrementType(type: ColumnType): String = when (type) {
        ColumnType.Scalar(SqlType.INTEGER), ColumnType.Scalar(SqlType.BIGINT) ->
            "${render(type)} GENERATED BY DEFAULT AS IDENTITY"
        else -> throw VolanDialectException("H2 autoincrement requires an Int or Long column.")
    }

    override fun createIndex(table: String, index: IndexDefinition): String {
        if (index.fullText) throw VolanDialectException("H2 full-text indexes require separately managed full-text tables.")
        return super.createIndex(table, index)
    }

    override fun alterColumn(alter: DdlStatement.AlterColumn): List<SqlStatement> = when (val change = alter.change) {
        is ColumnChange.Type -> listOf(
            SqlStatement(
                "ALTER TABLE ${quote(alter.table)} ALTER COLUMN ${quote(alter.column)} SET DATA TYPE ${render(change.type)}" +
                    change.using?.let { " USING $it" }.orEmpty(),
                emptyList(),
            ),
        )
        else -> super.alterColumn(alter)
    }

    override fun jdbcValue(value: Any?): Any? = when (value) {
        is Instant -> value.atOffset(ZoneOffset.UTC)
        is Json -> value.raw.toByteArray(Charsets.UTF_8)
        is List<*> -> value.map { jdbcValue(it) }.toTypedArray()
        else -> value
    }

    override fun sqlState(exception: SQLException): String? = when (exception.errorCode) {
        ErrorCode.REFERENTIAL_INTEGRITY_VIOLATED_PARENT_MISSING_1, ErrorCode.REFERENTIAL_INTEGRITY_VIOLATED_CHILD_EXISTS_1 -> "23503"
        ErrorCode.CHECK_CONSTRAINT_VIOLATED_1 -> "23514"
        ErrorCode.LOCK_TIMEOUT_1 -> "40001"
        else -> exception.sqlState
    }

    override fun poolSize(jdbcUrl: String, requested: Int): Int {
        require(requested > 0) { "a connection pool needs at least one connection" }
        val location = jdbcUrl.removePrefix("jdbc:h2:").substringBefore(';')
        return if (location == "mem:" || location == "mem") 1 else requested
    }

    // Retiring all connections to a memory database can erase its contents.
    override fun connectionMaxLifetime(jdbcUrl: String): Long? = if (jdbcUrl.startsWith("jdbc:h2:mem")) 0L else null
}
